name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: 'Deploy to Staging'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      ENVIRONMENT: stg
      APP_ENVIRONMENT: staging
      APP_GIT_TAG: ${{ github.ref }}
      ALLOWED_USERS: ${{ vars.STG_ALLOWED_USERS }}
